# Data Transformation in Pandas

Hi Guys, Welcome to [Tirendaz Academy](https://youtube.com/c/tirendazacademy) 😀
</br>
In this notebook, I'm going to show data transformation in Pandas.
</br>
Happy Learning 🐱‍🏍 

In [77]:
import pandas as pd

In [78]:
data=pd.DataFrame({"a":["one","two"]*3,
                   "b":[1,1,2,3,2,3]})
data

a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

In [79]:
data.duplicated() # return true if it's duplicated(el 4 esta en el 2, el 5 en el 3)

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [80]:
data.drop_duplicates() # drop the duplicated values

a  b
0  one  1
1  two  1
2  one  2
3  two  3

In [81]:
data["c"]=range(6) # add a new column
data

a  b  c
0  one  1  0
1  two  1  1
2  one  2  2
3  two  3  3
4  one  2  4
5  two  3  5

In [82]:
data.duplicated(["a","b"],keep="last") # keep the last duplicated value

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [83]:
df=pd.DataFrame({"names":["Tim","tom","Sam",
                          "kate","Kim"],
                "scores":[60,50,70,80,40]})
df

names  scores
0   Tim      60
1   tom      50
2   Sam      70
3  kate      80
4   Kim      40

In [84]:
classes={"Tim":"A","Tom":"A","Sam":"B",
         "Kate":"B","Kim":"B"}

In [85]:
n=df["names"].str.capitalize() # capitalize the first letter

In [86]:
df["branches"]=n.map(classes) # map the classes to the names

In [87]:
df

names  scores branches
0   Tim      60        A
1   tom      50        A
2   Sam      70        B
3  kate      80        B
4   Kim      40        B

In [88]:
s=pd.Series([80,70,90,60]) 
s

0    80
1    70
2    90
3    60
dtype: int64

In [89]:
import numpy as np

In [90]:
s.replace(70,np.nan) # replace 70 with nan

0    80.0
1     NaN
2    90.0
3    60.0
dtype: float64

In [91]:
s.replace([70,60],[np.nan,0]) # replace 70 with nan and 60 with 0

0    80.0
1     NaN
2    90.0
3     0.0
dtype: float64

In [92]:
s.replace({90:100,60:0}) # replace 90 with 100 and 60 with 0

0     80
1     70
2    100
3      0
dtype: int64

In [93]:
df=pd.DataFrame(
    np.arange(12).reshape(3,4),
    index=[0,1,2],
    columns=["tim","tom","kim","sam"])
df

tim  tom  kim  sam
0    0    1    2    3
1    4    5    6    7
2    8    9   10   11

In [94]:
s=pd.Series(["one","two","three"])
df.index=df.index.map(s) # map the index to the series

In [95]:
df

tim  tom  kim  sam
one      0    1    2    3
two      4    5    6    7
three    8    9   10   11

In [96]:
df.rename(index=str.title,columns=str.upper) # capitalize the index and upper the columns

TIM  TOM  KIM  SAM
One      0    1    2    3
Two      4    5    6    7
Three    8    9   10   11

In [97]:
df.rename(index={"one":"ten"},
          columns={"sam":"kate"}, #cambia uno por otro
          inplace=True) # rename the index and columns
df

tim  tom  kim  kate
ten      0    1    2     3
two      4    5    6     7
three    8    9   10    11

In [98]:
sc=[30,80,40,90,60,45,95,75,55,100,65,85] 

In [99]:
x=[20,40,60,80,100] # el valor 30 entra dentro de [20,40], el 80 en [80,100], etc

In [100]:
y=pd.cut(sc,x) # cut the data into bins
y

[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [101]:
y.codes # return the bin number #el 30 esta en el primer intervalo, el 80 en el tercero, etc

array([0, 2, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3], dtype=int8)

In [102]:
y.categories # return the bin range, el intervalo en el que esta cada valor

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]], dtype='interval[int64, right]')

In [103]:
pd.value_counts(y) # count the number of values in each bin

C:\Users\javie\AppData\Local\Temp\ipykernel_18328\4079270062.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(y) # count the number of values in each bin


(80, 100]    4
(40, 60]     3
(60, 80]     3
(20, 40]     2
Name: count, dtype: int64

In [104]:
y=pd.cut(sc,x,right=False) # right=False means the interval is left closed and right open (parecido a [a,b))
y

[[20, 40), [80, 100), [40, 60), [80, 100), [60, 80), ..., [60.0, 80.0), [40.0, 60.0), NaN, [60.0, 80.0), [80.0, 100.0)]
Length: 12
Categories (4, interval[int64, left]): [[20, 40) < [40, 60) < [60, 80) < [80, 100)]

In [105]:
nm=["low", "medium", "high", "very high"] # nombre de los intervalos
pd.cut(sc,x,labels=nm)

['low', 'high', 'low', 'very high', 'medium', ..., 'high', 'medium', 'very high', 'high', 'very high']
Length: 12
Categories (4, object): ['low' < 'medium' < 'high' < 'very high']

In [106]:
pd.cut(sc,10) # divide los datos en 10 intervalos

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (86.0, 93.0], (58.0, 65.0], ..., (72.0, 79.0], (51.0, 58.0], (93.0, 100.0], (58.0, 65.0], (79.0, 86.0]]
Length: 12
Categories (10, interval[float64, right]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] < (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] < (86.0, 93.0] < (93.0, 100.0]]

In [107]:
data=np.random.randn(100) # generate random data

print(data)
c=pd.qcut(data,4) # divide los datos en 4 intervalos
c

[ 6.36346878e-01  1.07155691e+00 -3.13549464e-01  1.17582220e+00
  4.08871257e-01 -1.01696826e+00  1.30772865e+00  5.05206197e-01
  4.23758369e-01 -3.75663085e-01  7.92517464e-01  1.32981729e+00
 -3.07224754e-01 -1.52237402e-01 -2.22134882e-01 -6.66864587e-01
  1.10749436e+00  7.32836203e-01 -2.41699066e+00  3.13443933e+00
 -2.07883985e-01 -3.12227732e+00 -7.54977119e-01  1.70022235e-01
 -2.76225586e-01  1.34735304e+00  1.53696227e+00 -9.29675710e-01
 -1.28697548e+00  1.92188978e-01 -1.10545175e+00 -1.33929416e+00
 -1.98620334e-01  1.09861071e+00  1.27649516e+00 -2.27858027e-02
 -3.78546382e-01 -2.51313277e-03 -8.67080006e-01 -3.95373461e-01
 -1.18401727e+00  1.54172598e+00  7.51711751e-01 -3.55296051e-01
  1.32043151e+00  1.87283240e+00 -4.66324315e-01 -9.25571086e-01
  3.14873949e-01  1.18079963e+00 -2.30409375e+00 -7.27421133e-01
 -1.10232091e+00 -5.50120806e-02 -4.87434602e-01  3.28448939e-01
  1.17790679e+00  5.48188088e-01  1.87085605e+00 -4.88356874e-01
  4.94977640e-01  5.12865

[(-0.0126, 1.083], (-0.0126, 1.083], (-0.724, -0.0126], (1.083, 3.134], (-0.0126, 1.083], ..., (1.083, 3.134], (-3.1229999999999998, -0.724], (-0.0126, 1.083], (-3.1229999999999998, -0.724], (-0.0126, 1.083]]
Length: 100
Categories (4, interval[float64, right]): [(-3.1229999999999998, -0.724] < (-0.724, -0.0126] < (-0.0126, 1.083] < (1.083, 3.134]]

In [108]:
pd.value_counts(c) # count the number of values in each bin

C:\Users\javie\AppData\Local\Temp\ipykernel_18328\1027987481.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(c) # count the number of values in each bin


(-3.1229999999999998, -0.724]    25
(-0.724, -0.0126]                25
(-0.0126, 1.083]                 25
(1.083, 3.134]                   25
Name: count, dtype: int64

In [109]:
data=pd.DataFrame(np.random.randn(1000,4)) #1000 filas y 4 columnas
data.head()

0         1         2         3
0 -0.058471 -0.846112 -1.120797 -0.417494
1 -0.459509  0.272834  0.129825  0.547768
2 -1.089628 -1.077206  0.790201 -0.876966
3  0.281401  1.443885 -0.878311  0.292991
4  0.051284  1.757781 -0.490810  0.755285

In [110]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.060532     0.006137    -0.020882    -0.039162
std       1.012872     0.993347     1.003293     0.977576
min      -4.220503    -3.070626    -4.027097    -3.602918
25%      -0.740550    -0.689801    -0.692570    -0.679569
50%      -0.090971    -0.024967    -0.012353    -0.068071
75%       0.654535     0.704501     0.679119     0.630390
max       2.927644     2.865050     3.087377     3.619535

In [111]:
col=data[1] # select the second column

In [112]:
col[np.abs(col)>3] # select the values greater than 3 or less than -3

606   -3.059151
628   -3.070626
Name: 1, dtype: float64

In [113]:
data[(np.abs(data)>3).any(axis=1)] # select the rows that have values greater than 3 or less than -3

0         1         2         3
10  -3.517440  0.235437  0.439853  0.551492
171 -3.333595  0.686419 -1.901233  1.133434
230  0.327122  1.145269  3.049002 -1.452742
476  1.948548  2.541366 -3.247603 -0.475801
521 -0.239727  1.299739  0.729846 -3.602918
528  0.951732 -0.472998  1.354082  3.175696
606  1.060584 -3.059151  0.630306 -0.841253
628 -1.337133 -3.070626  1.391153  1.020003
654 -1.360553 -0.669153  0.879926 -3.065507
680 -1.324877 -0.059060  3.087377 -0.035199
730 -1.431814  0.387125 -4.027097 -0.385891
790  0.704400  0.542733  0.207999  3.619535
792  0.594410 -0.819029 -3.301133 -1.487173
898 -4.220503 -0.146238  0.310707 -0.093195
948 -0.162442 -0.126870  0.707601  3.123026

In [114]:
np.sign(data).head() # return 1 if the value is positive, -1 if the value is negative, and 0 if the value is 0

0    1    2    3
0 -1.0 -1.0 -1.0 -1.0
1 -1.0  1.0  1.0  1.0
2 -1.0 -1.0  1.0 -1.0
3  1.0  1.0 -1.0  1.0
4  1.0  1.0 -1.0  1.0

In [115]:
data=pd.DataFrame(
    np.arange(12).reshape(4,3))
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [116]:
rw=np.random.permutation(4) # generate a random permutation of 4 ( devuelve una secuencia de estos números en un orden aleatorio(del 1 al 3).)
rw

array([3, 0, 1, 2], dtype=int32)

In [117]:
data.take(rw) # take the rows in the order of rw

0   1   2
3  9  10  11
0  0   1   2
1  3   4   5
2  6   7   8

In [118]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.sample() # select a random row

0         1         2         3
683  0.517782 -1.024856  0.697021 -0.193398

In [119]:
data = pd.DataFrame(np.random.randn(1000, 4))

data.sample(n=2) 

0         1         2         3
468 -1.918216 -0.167140  2.228589 -0.678641
727 -0.855105  0.825401  0.962361 -1.267767

## Dummy Variable

In [120]:
data=pd.DataFrame(
    {"letter":["c","b","a","b","b","a"],
                   "number":range(6)})
data

letter  number
0      c       0
1      b       1
2      a       2
3      b       3
4      b       4
5      a       5

In [121]:
pd.get_dummies(data["letter"]) # create dummy variables for the column "letter"
#la a tiene dos y cincos, la b tiene 1,3,4, la c tiene 0

a      b      c
0  False  False   True
1  False   True  False
2   True  False  False
3  False   True  False
4  False   True  False
5   True  False  False

In [122]:
data=np.random.randn(10) #10 números aleatorios, siguiendo una distribución normal
data

array([-1.63291963, -0.26740902, -0.48223651,  0.18620029, -0.54308953,
       -0.43967111, -0.65979126,  2.51947788,  0.74677451,  0.13756436])

In [123]:
pd.get_dummies(pd.cut(data,4)) # divide los datos en 4 bins, [-1.63291963] se encuentra en el intervalo (-1.637, -0.595], etc

(-1.637, -0.595]  (-0.595, 0.443]  (0.443, 1.481]  (1.481, 2.519]
0              True            False           False           False
1             False             True           False           False
2             False             True           False           False
3             False             True           False           False
4             False             True           False           False
5             False             True           False           False
6              True            False           False           False
7             False            False           False            True
8             False            False            True           False
9             False             True           False           False

Don't forget to follow us on [YouTube](http://youtube.com/tirendazacademy) | [Medium](http://tirendazacademy.medium.com) | [Twitter](http://twitter.com/tirendazacademy) | [GitHub](http://github.com/tirendazacademy) | [Linkedin](https://www.linkedin.com/in/tirendaz-academy) | [Kaggle](https://www.kaggle.com/tirendazacademy) 😎